"""make email nullable

Revision ID: 2d02f0f4c469
Revises: 
Create Date: 2025-09-10 13:43:48.808850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d02f0f4c469'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    # ### end Alembic commands ###
