"""add phone to clients

Revision ID: 674bb282106b
Revises: 0ac87a90e045
Create Date: 2025-09-13 17:07:20.841362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674bb282106b'
down_revision: Union[str, Sequence[str], None] = '0ac87a90e045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('clients', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('password', sa.String(length=100), nullable=False))
    op.add_column('clients', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=True))
    op.add_column('clients', sa.Column('district', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('cashback_balance', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'last_login')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'cashback_balance')
    op.drop_column('clients', 'is_premium')
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'interests')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'district')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'password')
    op.drop_column('clients', 'name')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
